#ifndef __TEST_H__
#define __TEST_H__

// #define TEST_MODE   TEST_NON_MEMBER
#define TEST_MODE   TEST_MEMBER
#define TEST_NON_MEMBER 0
#define TEST_MEMBER 1

#define TEST_UNPLUGGED          1
#define TEST_INIT_CP_INFO       2
#define TEST_UNTRANSMITTED_DATA_1       3
#define TEST_UNTRANSMITTED_DATA_2       4

#if (TEST_MODE == TEST_NON_MEMBER)
#define TEST_DATA_TRANSFER      0
#else 
// #define TEST_DATA_TRANSFER      TEST_UNPLUGGED
// #define TEST_DATA_TRANSFER      TEST_INIT_CP_INFO
// #define TEST_DATA_TRANSFER      TEST_UNTRANSMITTED_DATA_1
#define TEST_DATA_TRANSFER      TEST_UNTRANSMITTED_DATA_2
// #define TEST_DATA_TRANSFER      TEST_UNTRANSMITTED_DATA_3
#endif 

// #define TEST_AUTORIZE_MODE  TEST_AUTORIZE_COSTEL
#define TEST_AUTORIZE_MODE  TEST_AUTORIZE_CHARGEV
#define TEST_AUTORIZE_COSTEL    1
#define TEST_AUTORIZE_CHARGEV    2

#define SERVER_DEV  1
#define SERVER_LIV  2
#define SERVER_RUN  SERVER_DEV
// #define SERVER_RUN  SERVER_LIV

#endif 